version: '3'

services:
  frontend:
    build:
      context: ./heritage_ui
      dockerfile: Dockerfile
    networks:
      - app-network

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
